[package]
name = "proto-ql"
version = "0.1.0"
authors = ["Ansaf A <contact@ansaf.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
serde = { version = "1.0.106", features = ["derive"] }